name: Test PDF rendering
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile PDF document from rmd
        uses: ./
        with:
          input_file: test/pdf.Rmd
          output_format: pdf_document

